spring:
  application:
    name: banking-Backend-Quind
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_db
    username: postgres
    password: santiago
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Bogota

server:
  port: 8080

logging:
  level:
    com.prueba: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
